// src/components/Hero.svelte
<script lang="ts">
  import FadeInComponent from "./FadeInComponent.svelte";
  import AppStoreBtn from "./AppStoreBtn.svelte";
  import GooglePlayBtn from "./GooglePlayBtn.svelte";

  export let webm: string;
  export let mp4: string;
</script>

<FadeInComponent sectionName="start">
  <section
    class="w-screen flex justify-center items-center bg-bgDark1 mb-0 g:pb-0"
    id="start"
  >
    <div
      class="w-full sm:w-[800px] xl:w-[900px] flex flex-col justify-center items-center pt-16 sm:pt-16 lg:pt-20 text-center"
    >
      <h3
        class="text-secondaryColor text-sm sm:text-base mb-6 sm:mt-32 mt-16 font-bold"
      >
        PYROS WORLD
      </h3>

      <div
        class="text-5xl sm:text-6xl lg:text-7xl xl:text-7xl font-bold tracking-wide text-primaryText px-8 sm:px-8 lg:px-4"
      >
        <h1 class="inline">Radix's First 3D Battle Royale Game</h1>
      </div>

      <h2
        class="text-secondaryText text-sm lg:text-base xl:text-lg sm:text-base mt-10 px-12 sm:px-48"
      >
        Play-2-Earn by using gameable NFTs
      </h2>

      <div
        class="flex gap-3 sm:gap-12 sm:flex-row mt-8 mb-10 justify-center"
      >
        <AppStoreBtn />
        <GooglePlayBtn />
        <!-- <button
          class="contained-button w-64 sm:w-52 h-12 mr-0 sm:mr-4 lg:mr-6 mb-2 sm:mb-0"
          aria-label="Get started"
        >
          Get it on GooglePlay
        </button>
        <button
          class="w-64 sm:w-52 h-12 rounded-xl font-bold text-primaryText border border-solid flex justify-center items-center cursor-pointer bg-bgDark2 hover:bg-bgDark3 border-primaryColor transition"
          aria-label="Live demo"
        >
          Get it on AppStore
        </button> -->
      </div>

      <div class="relative w-screen flex justify-center">
        <video autoPlay muted loop class="w-full sm:w-10/12 2xl:w-[1200px] mx-auto z-10">
          <source src={mp4} type="video/mp4 codecs=hvc1" />
          <source src={webm} type="video/webm" />
        </video>
      </div>

      <!-- <div class="relative w-screen flex justify-center">
        <div
          class="shape-divider-bottom-1665343298 mt-4 sm:mt-16 hidden lg:block"
        >
          <svg
            data-name="Layer 1"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 1200 120"
            preserveAspectRatio="none"
            class="bg-bgDark2"
          >
            <path
              d="M1200 0L0 0 598.97 114.72 1200 0z"
              class="shape-fill bg-bgDark1 fill-bgDark1"
            ></path>
          </svg>
        </div>
      </div>  -->
    </div>
  </section>
</FadeInComponent>

// src/components/Hero.jsx
import { useState } from "react";
import { motion } from "framer-motion";

import { InvitationModal } from "./InvitationModal";
import trailerWebm from "../assets/videos/PyroTrailer.webm";
import trailerMP4 from "../assets/videos/PyroTrailer.mp4";

export const Hero = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <section
      className="w-screen  flex justify-center items-center bg-bgDark1 mb-[28vw] md:mb-[18vw] lg:mb-[10vw] xl:mb-[13vw] 2xl:mb-60 hero-bg-gradient pb-24 sm:pb-32 md:pb-44 lg:pb-0"
      id="home"
    >
      <div className="w-full md:w-[800px] xl:w-[900px] flex flex-col justify-center items-center pt-16 md:pt-16 lg:pt-20 text-center">
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h3 className="text-secondaryColor text-sm sm:text-base  mb-6 sm:mt-32 mt-16  font-bold">
            Discover new data flow
          </h3>
        </motion.div>
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.05 }}
        >
          <div className="text-5xl sm:text-6xl lg:text-7xl xl:text-7xl font-bold tracking-wide  text-primaryText  px-8 sm:px-8 md:px-20 lg:px-4">
            <h1 className="inline md:hidden">Analytics</h1>
            <h1 className="hidden md:inline">Analytic tools suite</h1>
          </div>
          <h1 className="mt-2 sm:mt-2 text-4xl sm:text-6xl lg:text-7xl xl:text-7xl font-bold tracking-wide  text-primaryText  px-8 sm:px-20 md:px-24 lg:px-24">
            for developers
          </h1>
        </motion.div>
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
        >
          <h2 className="text-secondaryText text-sm lg:text-base xl:text-lg sm:text-base mt-10 px-12 sm:px-48 ">
            Experience seamless business integrations and powerful insights with
            our cutting-edge analytic tools.
          </h2>
        </motion.div>
        <motion.div
         initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.15 }}
        >
          <div className="flex flex-col gap-2 sm:flex-row mt-14 mb-24 sm:mb-40 justify-center">
            <button
              className="contained-button w-64 sm:w-52 h-12 mr-0 sm:mr-4 lg:mr-6 mb-2 sm:mb-0"
              onClick={() => setIsModalOpen(true)}
              aria-label="Get started"
            >
              Get Started
            </button>
            <button
              className="w-64 sm:w-52 h-12 rounded-xl font-bold text-primaryText border border-solid  flex justify-center items-center cursor-pointer bg-bgDark2 hover:bg-bgDark3 border-primaryColor transition"
              onClick={() => setIsModalOpen(true)}
              aria-label="Live demo"
            >
              Live demo
            </button>
          </div>
        </motion.div>
        <motion.div
          initial={{ opacity: 0, y: 10, zIndex: 20 }}
          animate={{ opacity: 1, y: 0, zIndex: 20 }}
          transition={{ duration: 0.5, delay: 0.15 }}
        >
          <div className="relative w-screen flex justify-center ">
            {/* <img
              src={dashboard.src}
              alt="Dashboard image"
              className="w-4/5 2xl:w-[1200px] mx-auto absolute z-10 rounded-xl main-border-gray hero-dashboard-border-gradient lg:top-6 xl:top-0"
            /> */}


            <video autoPlay muted  className="w-4/5 2xl:w-[1200px] mx-auto absolute z-10 rounded-xl -mt-32 lg:top-6 xl:top-0">
            <source src={trailerMP4} type='video/mp4; codecs="hvc1"' />
            <source src={trailerWebm} type="video/webm" />
      </video>
      </div>
        </motion.div>
        <div className="relative w-screen flex justify-center ">
          <div className="shape-divider-bottom-1665343298 mt-4 sm:mt-16 md:mt-52 hidden lg:block">
            <svg
              data-name="Layer 1"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 1200 120"
              preserveAspectRatio="none"
              className="bg-bgDark2"
            >
              <path
                d="M1200 0L0 0 598.97 114.72 1200 0z"
                className="shape-fill bg-bgDark1  fill-bgDark1"
              ></path>
            </svg>
          </div>
        </div>
      </div>
      {isModalOpen && (
        <InvitationModal isOpen={isModalOpen} setIsOpen={setIsModalOpen} />
      )}
    </section>
  );
};
