// src/components/Navbar.jsx
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

import { TailcastLogo } from "../assets/logos/TailcastLogo";
import { GithubIcon } from "../assets/icons/GithubIcon";

const navbarLinks = [
  { label: "Start", href: "/", ariaLabel: "Start" },
  { label: "Roadmap", href: "/#roadmap", ariaLabel: "Roadmap" },
  { label: "Tokenomics", href: "/#tokenomics", ariaLabel: "Tokenomics" },
  { label: "Pre-Sale", href: "/pre-sale", ariaLabel: "Pre-Sale" },
  { label: "FAQ", href: "/#FAQ", ariaLabel: "FAQ" },
];

export const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <nav
      className="w-full h-20 flex flex-col justify-center items-center fixed bg-bgDark1 lg:bg-bgDarkTransparent z-40 lg:backdrop-blur-xl"
      aria-label="Main navigation"
    >
      <div className="2xl:w-[1280px] xl:w-10/12 w-11/12 flex justify-between items-center relative">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.3 }}
          exit={{ opacity: 0 }}
        >
          <a href="/#home" aria-label="Home">
            <div className="flex justify-start items-center grow basis-0">
              <div className="text-white mr-2 text-6xl">
                <TailcastLogo />
              </div>
              <div className="text-white font-['Inter'] font-bold text-xl">
                Tailcast
              </div>
            </div>
          </a>
        </motion.div>
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.3 }}
          exit={{ opacity: 0 }}
        >
          <div className="hidden lg:flex h-full pl-12 pb-2">
            {navbarLinks.map(({ href, label, ariaLabel }) => (
              <a
                className="text-white lg:text-base text-2xl  leading-6 mr-4 ml-4   2xl:mr-6 2xl:ml-6 cursor-pointer font-normal lg:font-medium hover:scale-110 transition h-full pt-2"
                href={href}
                aria-label={ariaLabel}
                key={label}
              >
                {label}
              </a>
            ))}
          </div>
        </motion.div>
       
        <div
          className="lg:hidden flex flex-col  px-2 py-3 border-solid border border-gray-600 rounded-md cursor-pointer hover:bg-bgDark2"
          onClick={() => setIsOpen(!isOpen)}
        >
          <div className="w-5 h-0.5 bg-gray-500  mb-1"></div>
          <div className="w-5 h-0.5 bg-gray-500  mb-1"></div>
          <div className="w-5 h-0.5 bg-gray-500 "></div>
        </div>
      </div>
      {/* Mobile navbar */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.3 }}
            exit={{ opacity: 0 }}
          >
            <div
              className="flex flex-col mt-16 lg:hidden absolute top-4 left-0  bg-bgDark1 z-50 w-full 
        items-center gap-10 pb-10 border-y border-solid border-bgDark3 pt-10
        "
            >
              {navbarLinks.map(({ label, href, ariaLabel }) => (
                <a
                  key={href}
                  className="text-white lg:text-base text-2xl  leading-6 mr-4 ml-4   2xl:mr-6 2xl:ml-6 cursor-pointer font-normal lg:font-medium hover:scale-110 transition duration-300 h-full pt-2"
                  href={href}
                  onClick={() => setIsOpen(false)}
                  aria-label={ariaLabel}
                >
                  {label}
                </a>
              ))}
        ´
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </nav>
  );
};

// src/components/Navbar.svelte
<script lang="ts">
  import PyroLogo from "../assets/logos/PyroLogo.svelte";
  import { fly } from "svelte/transition";
  import {section} from "../js/section.svelte";

  export let logo: string;

  let mobileOpen: boolean = false;

  const navbarLinks = [
    { label: "Start", href: "/#start", ariaLabel: "start" },    
    { label: "Pre-Sale", href: "/#pre-sale", ariaLabel: "presale" },
    { label: "Roadmap", href: "/#roadmap", ariaLabel: "roadmap" },
    { label: "Tokenomics", href: "/#tokenomics", ariaLabel: "tokenomics" },

    { label: "FAQ", href: "/#FAQ", ariaLabel: "FAQ" },
  ];
</script>

<nav
  class="w-full h-20 flex flex-col justify-center items-center fixed bg-bgDark1 lg:bg-bgDarkTransparent z-40 lg:backdrop-blur-xl"
  aria-label="Main navigation"
>
  <div
    class="2xl:w-[1280px] xl:w-10/12 w-11/12 flex justify-between items-center relative z-50"
  >
    <a href="/#start" aria-label="Start">
      <div class="flex justify-start items-center grow basis-0">
        <div class="text-white mr-2 text-6xl">
          <PyroLogo {logo} />
        </div>
        <div class="text-white font-['Inter'] font-bold text-xl">
          PYROS WORLD
        </div>
      </div>
    </a>

    <div class="hidden lg:flex h-full pl-12 pb-2 pt-2">
      {#each navbarLinks as link}
        <a
          class="lg:text-base text-2xl leading-6 mr-4 ml-4 2xl:mr-6 2xl:ml-6 cursor-pointer font-normal lg:font-medium  transition h-full pt-2
          {section.name === link.ariaLabel ? 'text-primaryColor scale-110' : 'text-white hover:scale-110'}"
          href={link.href}
          aria-label={link.ariaLabel}
        >
          {link.label}
        </a>
      {/each}
    </div>

    <button
      class="lg:hidden flex flex-col px-2 py-3 border-solid border border-gray-600 rounded-md cursor-pointer hover:bg-bgDark2"
      on:click={() => (mobileOpen = !mobileOpen)}
      aria-label="button"
    >
      <div class="w-5 h-0.5 bg-gray-500 mb-1"></div>
      <div class="w-5 h-0.5 bg-gray-500 mb-1"></div>
      <div class="w-5 h-0.5 bg-gray-500"></div>
    </button>
  </div>

  <!-- Mobile navbar *-->

  {#if mobileOpen}
    <div
      class="flex flex-col mt-16 absolute top-4 left-0 bg-bgDark1 w-full
        items-center gap-10 pb-10 border-y border-solid border-bgDark3 pt-10 z-40
        "
      transition:fly
    >
      {#each navbarLinks as link}
        <a
          class=" lg:text-base text-2xl leading-6 mr-4 ml-4 2xl:mr-6 2xl:ml-6 cursor-pointer font-normal lg:font-medium transition duration-300 h-full pt-2
           {section.name === link.ariaLabel ? 'text-primaryColor scale-110' : 'text-white hover:scale-110'}"
          href={link.href}
          aria-label={link.ariaLabel}
          on:click={() => mobileOpen = false}
        >
          {link.label}
        </a>
      {/each}
    </div>
  {/if}
</nav>
